### ISSUE TITLE
Order module missing

### ISSUE THREAD

**Issue by bajki** [laraplug/shop#1]
How to use if order module is missing?

Thanks

**Comment by darron1217** [comment]
Actually, I'm developing it now...
I'll update it now :)
Thanks for your interest

**Comment by darron1217** [comment]
I uploaded related modules and published version 0.3 beta
https://github.com/laraplug/shop/releases/tag/v0.3.0

Currently I don't have enough time to test installation working...
If there's problem, please submit an issue. I'll reply to it right away :)
